### ISSUE TITLE
localhost in email validation url

### ISSUE THREAD

**Issue by researcher1212** [SentinelDataHub/dhus-distribution#4]
Good day!

During user sign-in, email with verification url was received. But it starts with http:\\localhost:8081...

What changes should be made and in which config files?

P.S. In DHuS Administration Manual I didn't find this information.

**Comment by researcher1212** [comment]
And one more:
 changes in appconfig.json (AJS GUI) do not saved after stop and start DHuS server. (for example, "show_newgui_link" : false, after restart became true).

How to commit changes ?

**Comment by SentinelDataHub** [comment]
Hi @researcher1212 ,
First issue:
The file is: “dhus.xml” in etc folder. The parameter is:
server   
 external protocol="" host="" port="" path=""    
   server   
 
Further details are illustrated in the DHuS Administration Manual (p.58)

Second issue:
As indicate in the DHuS Administration Manual (p.69):    
"Once a value in the file has been changed, a simple refresh of the browser is necessary to see the change immediately applied. There is no need to restart the DHuS".
The configuration parameters changes are lost when you restart the DHuS. In the new coming version  this bug will be fixed.

Cheers
Sentinel Data Hub System Team

**Comment by researcher1212** [comment]
Thank's for quick response!
I set 
external protocol="http" host="blabla.bla" port="8081" path="#/home".

After restart DHuS server, tried to sign-in new user.
Got validation url like: "http://blabla.bla:8081/#/home/validation/e57acd05-b74f-4ccc-8d38-b9d332b45295cdbb53a543843ab2912a51e37f02aabe"

After followed it, the start page opened "http://blabla.bla:8081/#/home", but user still "isLocked = true"
What am I missing?

**Comment by researcher1212** [comment]
And another questions  :)
1. Switcher "Map layers" works only in "Road" mode. "Satellite" and "Hybrid" show black screen. Both of them using Class: MapQuest and layer: sat (according appconfig.json). Server has access to https://www.openstreetmap.org and http://nominatim.openstreetmap.org/ . 
What also I should check?

2. File scanner: tried to set path according to the DHuS Administration Manual (p.27): "if the products are in the same machine where DHuS is installed, the field shall be filled as ‘path/of/the/folder’".

Any of variants below didn't work:  "file:////home/dhus/" ; "home/dhus"; "home/dhus/" ; "/home/dhus/".
Which syntax would be correct if the products (zip archives) are on the following path: /home/dhus?

**Comment by SentinelDataHub** [comment]
Hi @researcher1212 ,
the configuration is:
server:external host="IP:8081"
path=""
port="80"
protocol="http"
or
port="443"
protocol="https"

1. Unfortunately, the current version doesn't support anymore these map layers. You can set new  map layers in appconfig.json file.   

2. The path should be:  /path/to/inbox/folder. The syntax is "/home/dhus/" .  


Cheers   
Sentinel DataHub System Team

**Comment by researcher1212** [comment]
Thank's!


All works, except upload scanner (see logs below):

[1.0.1-15-osf][2018-12-21 22:00:00,003][INFO ] SCHEDULER : Products scanners. (FileScannersJob.java:73 - jobScheduler_Worker-3)
[1.0.1-15-osf][2018-12-21 22:00:00,003][INFO ] Running FileScanners Executions. (FileScannersJob.java:80 - jobScheduler_Worker-3)
[1.0.1-15-osf][2018-12-21 22:00:00,030][INFO ] SCHEDULER : Products scanners done - 27ms (FileScannersJob.java:116 - jobScheduler_Worker-3)
[1.0.1-15-osf][2018-12-21 22:00:00,030][INFO ] root's fileScanner "/home/dhus/" started. (FileScannersJob.java:99 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:00,046][INFO ] Merge FileScanner spent 12ms (HibernateDao.java:119 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:01,795][INFO ] Product at 'file:/home/dhus/S2B_MSIL2A_20171227T091359_N0206_R050_T35TQN_20171227T115119.zip' is waiting for ingestion. (ScannerListener.java:63 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:01,800][INFO ] Product at 'file:/home/dhus/S2B_MSIL1C_20181216T085349_N0207_R107_T36UUA_20181216T110430.zip' is waiting for ingestion. (ScannerListener.java:63 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,619][ERROR] Exception in thread "scanner-job-1" java.lang.UnsupportedOperationException: cannot access repository path "/home/dhus/.mozilla/firefox/v2arv32f.default/lock". (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,619][ERROR]     at fr.gael.dhus.datastore.scanner.FileScanner.checkList(FileScanner.java:58) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.datastore.scanner.FileScanner.checkList(FileScanner.java:93) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.datastore.scanner.FileScanner.checkList(FileScanner.java:93) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.datastore.scanner.FileScanner.checkList(FileScanner.java:93) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.datastore.scanner.FileScanner.checkList(FileScanner.java:93) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.datastore.scanner.FileScanner.scan(FileScanner.java:111) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.datastore.scanner.ScannerFactory.processScan(ScannerFactory.java:276) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at fr.gael.dhus.service.job.FileScannersJob$1.run(FileScannersJob.java:101) (SystemLogHandler.java:267 - scanner-job-1)
[1.0.1-15-osf][2018-12-21 22:00:02,620][ERROR]     at java.lang.Thread.run(Thread.java:748) (SystemLogHandler.java:267 - scanner-job-1)

**Comment by SentinelDataHub** [comment]
Dear @researcher1212,
Our apologies in getting back to you so late.
In dhus.xml file you should check DataStores configuration, basically you can comment Datastores configuration if don't use them , or configure DataStores with the correct values as specified in the Administration Manual.

**Comment by researcher1212** [comment]
Thank's. I'll try.
